/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.haitao55.spider.common.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-02-20")
public class UrlModel implements org.apache.thrift.TBase<UrlModel, UrlModel._Fields>, java.io.Serializable, Cloneable, Comparable<UrlModel> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UrlModel");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("value", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PARENT_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("parentUrl", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField GRADE_FIELD_DESC = new org.apache.thrift.protocol.TField("grade", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField TASK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("taskId", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField LAST_CRAWLED_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("lastCrawledTime", org.apache.thrift.protocol.TType.I64, (short)7);
  private static final org.apache.thrift.protocol.TField LAST_CRAWLED_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("lastCrawledIP", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField URL_STATUS_MODEL_FIELD_DESC = new org.apache.thrift.protocol.TField("urlStatusModel", org.apache.thrift.protocol.TType.I32, (short)9);
  private static final org.apache.thrift.protocol.TField LATELY_ERROR_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("latelyErrorCode", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField LATELY_FAILED_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("latelyFailedCount", org.apache.thrift.protocol.TType.I32, (short)11);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("createTime", org.apache.thrift.protocol.TType.I64, (short)12);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UrlModelStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UrlModelTupleSchemeFactory());
  }

  public String id; // required
  public String value; // required
  public String parentUrl; // required
  public int grade; // required
  /**
   * 
   * @see UrlTypeModel
   */
  public UrlTypeModel type; // required
  public long taskId; // required
  public long lastCrawledTime; // required
  public String lastCrawledIP; // required
  /**
   * 
   * @see UrlStatusModel
   */
  public UrlStatusModel urlStatusModel; // required
  public String latelyErrorCode; // required
  public int latelyFailedCount; // required
  public long createTime; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    VALUE((short)2, "value"),
    PARENT_URL((short)3, "parentUrl"),
    GRADE((short)4, "grade"),
    /**
     * 
     * @see UrlTypeModel
     */
    TYPE((short)5, "type"),
    TASK_ID((short)6, "taskId"),
    LAST_CRAWLED_TIME((short)7, "lastCrawledTime"),
    LAST_CRAWLED_IP((short)8, "lastCrawledIP"),
    /**
     * 
     * @see UrlStatusModel
     */
    URL_STATUS_MODEL((short)9, "urlStatusModel"),
    LATELY_ERROR_CODE((short)10, "latelyErrorCode"),
    LATELY_FAILED_COUNT((short)11, "latelyFailedCount"),
    CREATE_TIME((short)12, "createTime");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // VALUE
          return VALUE;
        case 3: // PARENT_URL
          return PARENT_URL;
        case 4: // GRADE
          return GRADE;
        case 5: // TYPE
          return TYPE;
        case 6: // TASK_ID
          return TASK_ID;
        case 7: // LAST_CRAWLED_TIME
          return LAST_CRAWLED_TIME;
        case 8: // LAST_CRAWLED_IP
          return LAST_CRAWLED_IP;
        case 9: // URL_STATUS_MODEL
          return URL_STATUS_MODEL;
        case 10: // LATELY_ERROR_CODE
          return LATELY_ERROR_CODE;
        case 11: // LATELY_FAILED_COUNT
          return LATELY_FAILED_COUNT;
        case 12: // CREATE_TIME
          return CREATE_TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __GRADE_ISSET_ID = 0;
  private static final int __TASKID_ISSET_ID = 1;
  private static final int __LASTCRAWLEDTIME_ISSET_ID = 2;
  private static final int __LATELYFAILEDCOUNT_ISSET_ID = 3;
  private static final int __CREATETIME_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VALUE, new org.apache.thrift.meta_data.FieldMetaData("value", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PARENT_URL, new org.apache.thrift.meta_data.FieldMetaData("parentUrl", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.GRADE, new org.apache.thrift.meta_data.FieldMetaData("grade", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, UrlTypeModel.class)));
    tmpMap.put(_Fields.TASK_ID, new org.apache.thrift.meta_data.FieldMetaData("taskId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.LAST_CRAWLED_TIME, new org.apache.thrift.meta_data.FieldMetaData("lastCrawledTime", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.LAST_CRAWLED_IP, new org.apache.thrift.meta_data.FieldMetaData("lastCrawledIP", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.URL_STATUS_MODEL, new org.apache.thrift.meta_data.FieldMetaData("urlStatusModel", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, UrlStatusModel.class)));
    tmpMap.put(_Fields.LATELY_ERROR_CODE, new org.apache.thrift.meta_data.FieldMetaData("latelyErrorCode", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LATELY_FAILED_COUNT, new org.apache.thrift.meta_data.FieldMetaData("latelyFailedCount", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("createTime", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UrlModel.class, metaDataMap);
  }

  public UrlModel() {
  }

  public UrlModel(
    String id,
    String value,
    String parentUrl,
    int grade,
    UrlTypeModel type,
    long taskId,
    long lastCrawledTime,
    String lastCrawledIP,
    UrlStatusModel urlStatusModel,
    String latelyErrorCode,
    int latelyFailedCount,
    long createTime)
  {
    this();
    this.id = id;
    this.value = value;
    this.parentUrl = parentUrl;
    this.grade = grade;
    setGradeIsSet(true);
    this.type = type;
    this.taskId = taskId;
    setTaskIdIsSet(true);
    this.lastCrawledTime = lastCrawledTime;
    setLastCrawledTimeIsSet(true);
    this.lastCrawledIP = lastCrawledIP;
    this.urlStatusModel = urlStatusModel;
    this.latelyErrorCode = latelyErrorCode;
    this.latelyFailedCount = latelyFailedCount;
    setLatelyFailedCountIsSet(true);
    this.createTime = createTime;
    setCreateTimeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UrlModel(UrlModel other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetId()) {
      this.id = other.id;
    }
    if (other.isSetValue()) {
      this.value = other.value;
    }
    if (other.isSetParentUrl()) {
      this.parentUrl = other.parentUrl;
    }
    this.grade = other.grade;
    if (other.isSetType()) {
      this.type = other.type;
    }
    this.taskId = other.taskId;
    this.lastCrawledTime = other.lastCrawledTime;
    if (other.isSetLastCrawledIP()) {
      this.lastCrawledIP = other.lastCrawledIP;
    }
    if (other.isSetUrlStatusModel()) {
      this.urlStatusModel = other.urlStatusModel;
    }
    if (other.isSetLatelyErrorCode()) {
      this.latelyErrorCode = other.latelyErrorCode;
    }
    this.latelyFailedCount = other.latelyFailedCount;
    this.createTime = other.createTime;
  }

  public UrlModel deepCopy() {
    return new UrlModel(this);
  }

  @Override
  public void clear() {
    this.id = null;
    this.value = null;
    this.parentUrl = null;
    setGradeIsSet(false);
    this.grade = 0;
    this.type = null;
    setTaskIdIsSet(false);
    this.taskId = 0;
    setLastCrawledTimeIsSet(false);
    this.lastCrawledTime = 0;
    this.lastCrawledIP = null;
    this.urlStatusModel = null;
    this.latelyErrorCode = null;
    setLatelyFailedCountIsSet(false);
    this.latelyFailedCount = 0;
    setCreateTimeIsSet(false);
    this.createTime = 0;
  }

  public String getId() {
    return this.id;
  }

  public UrlModel setId(String id) {
    this.id = id;
    return this;
  }

  public void unsetId() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return this.id != null;
  }

  public void setIdIsSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  public String getValue() {
    return this.value;
  }

  public UrlModel setValue(String value) {
    this.value = value;
    return this;
  }

  public void unsetValue() {
    this.value = null;
  }

  /** Returns true if field value is set (has been assigned a value) and false otherwise */
  public boolean isSetValue() {
    return this.value != null;
  }

  public void setValueIsSet(boolean value) {
    if (!value) {
      this.value = null;
    }
  }

  public String getParentUrl() {
    return this.parentUrl;
  }

  public UrlModel setParentUrl(String parentUrl) {
    this.parentUrl = parentUrl;
    return this;
  }

  public void unsetParentUrl() {
    this.parentUrl = null;
  }

  /** Returns true if field parentUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetParentUrl() {
    return this.parentUrl != null;
  }

  public void setParentUrlIsSet(boolean value) {
    if (!value) {
      this.parentUrl = null;
    }
  }

  public int getGrade() {
    return this.grade;
  }

  public UrlModel setGrade(int grade) {
    this.grade = grade;
    setGradeIsSet(true);
    return this;
  }

  public void unsetGrade() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __GRADE_ISSET_ID);
  }

  /** Returns true if field grade is set (has been assigned a value) and false otherwise */
  public boolean isSetGrade() {
    return EncodingUtils.testBit(__isset_bitfield, __GRADE_ISSET_ID);
  }

  public void setGradeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __GRADE_ISSET_ID, value);
  }

  /**
   * 
   * @see UrlTypeModel
   */
  public UrlTypeModel getType() {
    return this.type;
  }

  /**
   * 
   * @see UrlTypeModel
   */
  public UrlModel setType(UrlTypeModel type) {
    this.type = type;
    return this;
  }

  public void unsetType() {
    this.type = null;
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return this.type != null;
  }

  public void setTypeIsSet(boolean value) {
    if (!value) {
      this.type = null;
    }
  }

  public long getTaskId() {
    return this.taskId;
  }

  public UrlModel setTaskId(long taskId) {
    this.taskId = taskId;
    setTaskIdIsSet(true);
    return this;
  }

  public void unsetTaskId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TASKID_ISSET_ID);
  }

  /** Returns true if field taskId is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskId() {
    return EncodingUtils.testBit(__isset_bitfield, __TASKID_ISSET_ID);
  }

  public void setTaskIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TASKID_ISSET_ID, value);
  }

  public long getLastCrawledTime() {
    return this.lastCrawledTime;
  }

  public UrlModel setLastCrawledTime(long lastCrawledTime) {
    this.lastCrawledTime = lastCrawledTime;
    setLastCrawledTimeIsSet(true);
    return this;
  }

  public void unsetLastCrawledTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LASTCRAWLEDTIME_ISSET_ID);
  }

  /** Returns true if field lastCrawledTime is set (has been assigned a value) and false otherwise */
  public boolean isSetLastCrawledTime() {
    return EncodingUtils.testBit(__isset_bitfield, __LASTCRAWLEDTIME_ISSET_ID);
  }

  public void setLastCrawledTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LASTCRAWLEDTIME_ISSET_ID, value);
  }

  public String getLastCrawledIP() {
    return this.lastCrawledIP;
  }

  public UrlModel setLastCrawledIP(String lastCrawledIP) {
    this.lastCrawledIP = lastCrawledIP;
    return this;
  }

  public void unsetLastCrawledIP() {
    this.lastCrawledIP = null;
  }

  /** Returns true if field lastCrawledIP is set (has been assigned a value) and false otherwise */
  public boolean isSetLastCrawledIP() {
    return this.lastCrawledIP != null;
  }

  public void setLastCrawledIPIsSet(boolean value) {
    if (!value) {
      this.lastCrawledIP = null;
    }
  }

  /**
   * 
   * @see UrlStatusModel
   */
  public UrlStatusModel getUrlStatusModel() {
    return this.urlStatusModel;
  }

  /**
   * 
   * @see UrlStatusModel
   */
  public UrlModel setUrlStatusModel(UrlStatusModel urlStatusModel) {
    this.urlStatusModel = urlStatusModel;
    return this;
  }

  public void unsetUrlStatusModel() {
    this.urlStatusModel = null;
  }

  /** Returns true if field urlStatusModel is set (has been assigned a value) and false otherwise */
  public boolean isSetUrlStatusModel() {
    return this.urlStatusModel != null;
  }

  public void setUrlStatusModelIsSet(boolean value) {
    if (!value) {
      this.urlStatusModel = null;
    }
  }

  public String getLatelyErrorCode() {
    return this.latelyErrorCode;
  }

  public UrlModel setLatelyErrorCode(String latelyErrorCode) {
    this.latelyErrorCode = latelyErrorCode;
    return this;
  }

  public void unsetLatelyErrorCode() {
    this.latelyErrorCode = null;
  }

  /** Returns true if field latelyErrorCode is set (has been assigned a value) and false otherwise */
  public boolean isSetLatelyErrorCode() {
    return this.latelyErrorCode != null;
  }

  public void setLatelyErrorCodeIsSet(boolean value) {
    if (!value) {
      this.latelyErrorCode = null;
    }
  }

  public int getLatelyFailedCount() {
    return this.latelyFailedCount;
  }

  public UrlModel setLatelyFailedCount(int latelyFailedCount) {
    this.latelyFailedCount = latelyFailedCount;
    setLatelyFailedCountIsSet(true);
    return this;
  }

  public void unsetLatelyFailedCount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LATELYFAILEDCOUNT_ISSET_ID);
  }

  /** Returns true if field latelyFailedCount is set (has been assigned a value) and false otherwise */
  public boolean isSetLatelyFailedCount() {
    return EncodingUtils.testBit(__isset_bitfield, __LATELYFAILEDCOUNT_ISSET_ID);
  }

  public void setLatelyFailedCountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LATELYFAILEDCOUNT_ISSET_ID, value);
  }

  public long getCreateTime() {
    return this.createTime;
  }

  public UrlModel setCreateTime(long createTime) {
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    return this;
  }

  public void unsetCreateTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return EncodingUtils.testBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  public void setCreateTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CREATETIME_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((String)value);
      }
      break;

    case VALUE:
      if (value == null) {
        unsetValue();
      } else {
        setValue((String)value);
      }
      break;

    case PARENT_URL:
      if (value == null) {
        unsetParentUrl();
      } else {
        setParentUrl((String)value);
      }
      break;

    case GRADE:
      if (value == null) {
        unsetGrade();
      } else {
        setGrade((Integer)value);
      }
      break;

    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((UrlTypeModel)value);
      }
      break;

    case TASK_ID:
      if (value == null) {
        unsetTaskId();
      } else {
        setTaskId((Long)value);
      }
      break;

    case LAST_CRAWLED_TIME:
      if (value == null) {
        unsetLastCrawledTime();
      } else {
        setLastCrawledTime((Long)value);
      }
      break;

    case LAST_CRAWLED_IP:
      if (value == null) {
        unsetLastCrawledIP();
      } else {
        setLastCrawledIP((String)value);
      }
      break;

    case URL_STATUS_MODEL:
      if (value == null) {
        unsetUrlStatusModel();
      } else {
        setUrlStatusModel((UrlStatusModel)value);
      }
      break;

    case LATELY_ERROR_CODE:
      if (value == null) {
        unsetLatelyErrorCode();
      } else {
        setLatelyErrorCode((String)value);
      }
      break;

    case LATELY_FAILED_COUNT:
      if (value == null) {
        unsetLatelyFailedCount();
      } else {
        setLatelyFailedCount((Integer)value);
      }
      break;

    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case VALUE:
      return getValue();

    case PARENT_URL:
      return getParentUrl();

    case GRADE:
      return getGrade();

    case TYPE:
      return getType();

    case TASK_ID:
      return getTaskId();

    case LAST_CRAWLED_TIME:
      return getLastCrawledTime();

    case LAST_CRAWLED_IP:
      return getLastCrawledIP();

    case URL_STATUS_MODEL:
      return getUrlStatusModel();

    case LATELY_ERROR_CODE:
      return getLatelyErrorCode();

    case LATELY_FAILED_COUNT:
      return getLatelyFailedCount();

    case CREATE_TIME:
      return getCreateTime();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case VALUE:
      return isSetValue();
    case PARENT_URL:
      return isSetParentUrl();
    case GRADE:
      return isSetGrade();
    case TYPE:
      return isSetType();
    case TASK_ID:
      return isSetTaskId();
    case LAST_CRAWLED_TIME:
      return isSetLastCrawledTime();
    case LAST_CRAWLED_IP:
      return isSetLastCrawledIP();
    case URL_STATUS_MODEL:
      return isSetUrlStatusModel();
    case LATELY_ERROR_CODE:
      return isSetLatelyErrorCode();
    case LATELY_FAILED_COUNT:
      return isSetLatelyFailedCount();
    case CREATE_TIME:
      return isSetCreateTime();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UrlModel)
      return this.equals((UrlModel)that);
    return false;
  }

  public boolean equals(UrlModel that) {
    if (that == null)
      return false;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_value = true && this.isSetValue();
    boolean that_present_value = true && that.isSetValue();
    if (this_present_value || that_present_value) {
      if (!(this_present_value && that_present_value))
        return false;
      if (!this.value.equals(that.value))
        return false;
    }

    boolean this_present_parentUrl = true && this.isSetParentUrl();
    boolean that_present_parentUrl = true && that.isSetParentUrl();
    if (this_present_parentUrl || that_present_parentUrl) {
      if (!(this_present_parentUrl && that_present_parentUrl))
        return false;
      if (!this.parentUrl.equals(that.parentUrl))
        return false;
    }

    boolean this_present_grade = true;
    boolean that_present_grade = true;
    if (this_present_grade || that_present_grade) {
      if (!(this_present_grade && that_present_grade))
        return false;
      if (this.grade != that.grade)
        return false;
    }

    boolean this_present_type = true && this.isSetType();
    boolean that_present_type = true && that.isSetType();
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (!this.type.equals(that.type))
        return false;
    }

    boolean this_present_taskId = true;
    boolean that_present_taskId = true;
    if (this_present_taskId || that_present_taskId) {
      if (!(this_present_taskId && that_present_taskId))
        return false;
      if (this.taskId != that.taskId)
        return false;
    }

    boolean this_present_lastCrawledTime = true;
    boolean that_present_lastCrawledTime = true;
    if (this_present_lastCrawledTime || that_present_lastCrawledTime) {
      if (!(this_present_lastCrawledTime && that_present_lastCrawledTime))
        return false;
      if (this.lastCrawledTime != that.lastCrawledTime)
        return false;
    }

    boolean this_present_lastCrawledIP = true && this.isSetLastCrawledIP();
    boolean that_present_lastCrawledIP = true && that.isSetLastCrawledIP();
    if (this_present_lastCrawledIP || that_present_lastCrawledIP) {
      if (!(this_present_lastCrawledIP && that_present_lastCrawledIP))
        return false;
      if (!this.lastCrawledIP.equals(that.lastCrawledIP))
        return false;
    }

    boolean this_present_urlStatusModel = true && this.isSetUrlStatusModel();
    boolean that_present_urlStatusModel = true && that.isSetUrlStatusModel();
    if (this_present_urlStatusModel || that_present_urlStatusModel) {
      if (!(this_present_urlStatusModel && that_present_urlStatusModel))
        return false;
      if (!this.urlStatusModel.equals(that.urlStatusModel))
        return false;
    }

    boolean this_present_latelyErrorCode = true && this.isSetLatelyErrorCode();
    boolean that_present_latelyErrorCode = true && that.isSetLatelyErrorCode();
    if (this_present_latelyErrorCode || that_present_latelyErrorCode) {
      if (!(this_present_latelyErrorCode && that_present_latelyErrorCode))
        return false;
      if (!this.latelyErrorCode.equals(that.latelyErrorCode))
        return false;
    }

    boolean this_present_latelyFailedCount = true;
    boolean that_present_latelyFailedCount = true;
    if (this_present_latelyFailedCount || that_present_latelyFailedCount) {
      if (!(this_present_latelyFailedCount && that_present_latelyFailedCount))
        return false;
      if (this.latelyFailedCount != that.latelyFailedCount)
        return false;
    }

    boolean this_present_createTime = true;
    boolean that_present_createTime = true;
    if (this_present_createTime || that_present_createTime) {
      if (!(this_present_createTime && that_present_createTime))
        return false;
      if (this.createTime != that.createTime)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_id = true && (isSetId());
    list.add(present_id);
    if (present_id)
      list.add(id);

    boolean present_value = true && (isSetValue());
    list.add(present_value);
    if (present_value)
      list.add(value);

    boolean present_parentUrl = true && (isSetParentUrl());
    list.add(present_parentUrl);
    if (present_parentUrl)
      list.add(parentUrl);

    boolean present_grade = true;
    list.add(present_grade);
    if (present_grade)
      list.add(grade);

    boolean present_type = true && (isSetType());
    list.add(present_type);
    if (present_type)
      list.add(type.getValue());

    boolean present_taskId = true;
    list.add(present_taskId);
    if (present_taskId)
      list.add(taskId);

    boolean present_lastCrawledTime = true;
    list.add(present_lastCrawledTime);
    if (present_lastCrawledTime)
      list.add(lastCrawledTime);

    boolean present_lastCrawledIP = true && (isSetLastCrawledIP());
    list.add(present_lastCrawledIP);
    if (present_lastCrawledIP)
      list.add(lastCrawledIP);

    boolean present_urlStatusModel = true && (isSetUrlStatusModel());
    list.add(present_urlStatusModel);
    if (present_urlStatusModel)
      list.add(urlStatusModel.getValue());

    boolean present_latelyErrorCode = true && (isSetLatelyErrorCode());
    list.add(present_latelyErrorCode);
    if (present_latelyErrorCode)
      list.add(latelyErrorCode);

    boolean present_latelyFailedCount = true;
    list.add(present_latelyFailedCount);
    if (present_latelyFailedCount)
      list.add(latelyFailedCount);

    boolean present_createTime = true;
    list.add(present_createTime);
    if (present_createTime)
      list.add(createTime);

    return list.hashCode();
  }

  @Override
  public int compareTo(UrlModel other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetValue()).compareTo(other.isSetValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.value, other.value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetParentUrl()).compareTo(other.isSetParentUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParentUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.parentUrl, other.parentUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetGrade()).compareTo(other.isSetGrade());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGrade()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.grade, other.grade);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetType()).compareTo(other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTaskId()).compareTo(other.isSetTaskId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskId, other.taskId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastCrawledTime()).compareTo(other.isSetLastCrawledTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastCrawledTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastCrawledTime, other.lastCrawledTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastCrawledIP()).compareTo(other.isSetLastCrawledIP());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastCrawledIP()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastCrawledIP, other.lastCrawledIP);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUrlStatusModel()).compareTo(other.isSetUrlStatusModel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUrlStatusModel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.urlStatusModel, other.urlStatusModel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLatelyErrorCode()).compareTo(other.isSetLatelyErrorCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLatelyErrorCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.latelyErrorCode, other.latelyErrorCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLatelyFailedCount()).compareTo(other.isSetLatelyFailedCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLatelyFailedCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.latelyFailedCount, other.latelyFailedCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreateTime()).compareTo(other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UrlModel(");
    boolean first = true;

    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("value:");
    if (this.value == null) {
      sb.append("null");
    } else {
      sb.append(this.value);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("parentUrl:");
    if (this.parentUrl == null) {
      sb.append("null");
    } else {
      sb.append(this.parentUrl);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("grade:");
    sb.append(this.grade);
    first = false;
    if (!first) sb.append(", ");
    sb.append("type:");
    if (this.type == null) {
      sb.append("null");
    } else {
      sb.append(this.type);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("taskId:");
    sb.append(this.taskId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastCrawledTime:");
    sb.append(this.lastCrawledTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastCrawledIP:");
    if (this.lastCrawledIP == null) {
      sb.append("null");
    } else {
      sb.append(this.lastCrawledIP);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("urlStatusModel:");
    if (this.urlStatusModel == null) {
      sb.append("null");
    } else {
      sb.append(this.urlStatusModel);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("latelyErrorCode:");
    if (this.latelyErrorCode == null) {
      sb.append("null");
    } else {
      sb.append(this.latelyErrorCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("latelyFailedCount:");
    sb.append(this.latelyFailedCount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("createTime:");
    sb.append(this.createTime);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (id == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'id' was not present! Struct: " + toString());
    }
    if (value == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'value' was not present! Struct: " + toString());
    }
    if (parentUrl == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'parentUrl' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'grade' because it's a primitive and you chose the non-beans generator.
    if (type == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'type' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'taskId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'lastCrawledTime' because it's a primitive and you chose the non-beans generator.
    if (lastCrawledIP == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'lastCrawledIP' was not present! Struct: " + toString());
    }
    if (urlStatusModel == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'urlStatusModel' was not present! Struct: " + toString());
    }
    if (latelyErrorCode == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'latelyErrorCode' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'latelyFailedCount' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'createTime' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UrlModelStandardSchemeFactory implements SchemeFactory {
    public UrlModelStandardScheme getScheme() {
      return new UrlModelStandardScheme();
    }
  }

  private static class UrlModelStandardScheme extends StandardScheme<UrlModel> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UrlModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id = iprot.readString();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.value = iprot.readString();
              struct.setValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PARENT_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.parentUrl = iprot.readString();
              struct.setParentUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // GRADE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.grade = iprot.readI32();
              struct.setGradeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = com.haitao55.spider.common.thrift.UrlTypeModel.findByValue(iprot.readI32());
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // TASK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.taskId = iprot.readI64();
              struct.setTaskIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // LAST_CRAWLED_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastCrawledTime = iprot.readI64();
              struct.setLastCrawledTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // LAST_CRAWLED_IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lastCrawledIP = iprot.readString();
              struct.setLastCrawledIPIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // URL_STATUS_MODEL
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.urlStatusModel = com.haitao55.spider.common.thrift.UrlStatusModel.findByValue(iprot.readI32());
              struct.setUrlStatusModelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // LATELY_ERROR_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.latelyErrorCode = iprot.readString();
              struct.setLatelyErrorCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // LATELY_FAILED_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.latelyFailedCount = iprot.readI32();
              struct.setLatelyFailedCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTime = iprot.readI64();
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetGrade()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'grade' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetTaskId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'taskId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetLastCrawledTime()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'lastCrawledTime' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetLatelyFailedCount()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'latelyFailedCount' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetCreateTime()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'createTime' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UrlModel struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.value != null) {
        oprot.writeFieldBegin(VALUE_FIELD_DESC);
        oprot.writeString(struct.value);
        oprot.writeFieldEnd();
      }
      if (struct.parentUrl != null) {
        oprot.writeFieldBegin(PARENT_URL_FIELD_DESC);
        oprot.writeString(struct.parentUrl);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(GRADE_FIELD_DESC);
      oprot.writeI32(struct.grade);
      oprot.writeFieldEnd();
      if (struct.type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.type.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TASK_ID_FIELD_DESC);
      oprot.writeI64(struct.taskId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LAST_CRAWLED_TIME_FIELD_DESC);
      oprot.writeI64(struct.lastCrawledTime);
      oprot.writeFieldEnd();
      if (struct.lastCrawledIP != null) {
        oprot.writeFieldBegin(LAST_CRAWLED_IP_FIELD_DESC);
        oprot.writeString(struct.lastCrawledIP);
        oprot.writeFieldEnd();
      }
      if (struct.urlStatusModel != null) {
        oprot.writeFieldBegin(URL_STATUS_MODEL_FIELD_DESC);
        oprot.writeI32(struct.urlStatusModel.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.latelyErrorCode != null) {
        oprot.writeFieldBegin(LATELY_ERROR_CODE_FIELD_DESC);
        oprot.writeString(struct.latelyErrorCode);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(LATELY_FAILED_COUNT_FIELD_DESC);
      oprot.writeI32(struct.latelyFailedCount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
      oprot.writeI64(struct.createTime);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UrlModelTupleSchemeFactory implements SchemeFactory {
    public UrlModelTupleScheme getScheme() {
      return new UrlModelTupleScheme();
    }
  }

  private static class UrlModelTupleScheme extends TupleScheme<UrlModel> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UrlModel struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.id);
      oprot.writeString(struct.value);
      oprot.writeString(struct.parentUrl);
      oprot.writeI32(struct.grade);
      oprot.writeI32(struct.type.getValue());
      oprot.writeI64(struct.taskId);
      oprot.writeI64(struct.lastCrawledTime);
      oprot.writeString(struct.lastCrawledIP);
      oprot.writeI32(struct.urlStatusModel.getValue());
      oprot.writeString(struct.latelyErrorCode);
      oprot.writeI32(struct.latelyFailedCount);
      oprot.writeI64(struct.createTime);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UrlModel struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.id = iprot.readString();
      struct.setIdIsSet(true);
      struct.value = iprot.readString();
      struct.setValueIsSet(true);
      struct.parentUrl = iprot.readString();
      struct.setParentUrlIsSet(true);
      struct.grade = iprot.readI32();
      struct.setGradeIsSet(true);
      struct.type = com.haitao55.spider.common.thrift.UrlTypeModel.findByValue(iprot.readI32());
      struct.setTypeIsSet(true);
      struct.taskId = iprot.readI64();
      struct.setTaskIdIsSet(true);
      struct.lastCrawledTime = iprot.readI64();
      struct.setLastCrawledTimeIsSet(true);
      struct.lastCrawledIP = iprot.readString();
      struct.setLastCrawledIPIsSet(true);
      struct.urlStatusModel = com.haitao55.spider.common.thrift.UrlStatusModel.findByValue(iprot.readI32());
      struct.setUrlStatusModelIsSet(true);
      struct.latelyErrorCode = iprot.readString();
      struct.setLatelyErrorCodeIsSet(true);
      struct.latelyFailedCount = iprot.readI32();
      struct.setLatelyFailedCountIsSet(true);
      struct.createTime = iprot.readI64();
      struct.setCreateTimeIsSet(true);
    }
  }

}

