/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.haitao55.spider.common.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum UrlTypeModel implements org.apache.thrift.TEnum {
  LINK(0),
  ITEM(1);

  private final int value;

  private UrlTypeModel(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static UrlTypeModel findByValue(int value) { 
    switch (value) {
      case 0:
        return LINK;
      case 1:
        return ITEM;
      default:
        return null;
    }
  }
}
